[window]

startup_mode = "Maximized"

title = "Alacritty"

dynamic_title = true 

# padding = { x = 1, y = 0 }

decorations = "None"

opacity = 1.0

dynamic_padding = true



[scrolling]

history = 10000



[font]

normal = { family = "CaskaydiaCove Nerd Font Mono" }

bold = { family = "CaskaydiaCove Nerd Font Mono" }

italic = { family = "CaskaydiaCove Nerd Font Mono" }

bold_italic = { family = "CaskaydiaCove Nerd Font Mono" }

size = 20


[colors]

cursor = { text = "#ffffff", cursor = "CellForeground" }

vi_mode_cursor = { text = "#ffffff", cursor = "CellForeground" }

transparent_background_colors = true

draw_bold_text_with_bright_colors = true

[colors.primary]

foreground = "#ffffff"
background = "#222222"
dim_foreground = "#ffffff"

[colors.normal]

black = "#282C34"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#ffffff"


[selection]

save_to_clipboard = true


[cursor]

style = { shape = "Block", blinking = "Always" }

vi_mode_style = { shape = "Block", blinking = "Always" }


[terminal]

# Open PowerShell 
shell = {program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe", args = ["-NoExit", "-Command", "Set-Location 'D:\\Github'"]}

# Open Ubuntu WSL
# shell = { program = "C:\\WINDOWS\\system32\\wsl.exe", args = [ "--distribution-id", "{d04271a6-07cb-4d54-8597-054eaaecbcdf}", "--cd", "~" ]}




